
demo1_mac_gen:
	protoc -I $${GOPATH}/src --go_out=plugins=grpc:$${GOPATH}/src $${GOPATH}/src/github.com/razeencheng/demo-go/grpc/demo1/helloworld/hello_world.proto

demo1_win_gen:
	protoc -I $$env:GOPATH\src --go_out=plugins=grpc:$$env:GOPATH\src $$env:GOPATH\src\github.com\razeencheng\demo-go\grpc\demo1\helloworld\hello_world.proto